#################################################
#监狱位置
监狱所在的世界: world
监狱X坐标: 0.00
监狱Y坐标: 0.00
监狱Z坐标: 0.00
#################################################
#插件设置
是否在进入监狱前清空玩家物品: false
小黑屋最大人数: 20
#################################################
